openLoop0/name: RiC_Open_Motor
openLoop0/address: 128
openLoop0/channel: 1
openLoop0/timeout: 1000
openLoop0/max: 127
openLoop1/name: RiC_Open_Motor1
openLoop1/address: 128
openLoop1/channel: 1
openLoop1/timeout: 1000
openLoop1/max: 12
IMU_INIT: 0
GPS_INIT: 0
PPM_INIT: 0
DIFF_INIT: 0
closeLoopNum: 0
switchNum: 0
servoNum: 0
relayNum: 0
URFNum: 0
openLoopNum: 2
